return {
-- "ray-x/navigator.lua",
--     dependencies = {
--         {"hrsh7th/nvim-cmp"}, {"nvim-treesitter/nvim-treesitter"},
--         {"ray-x/guihua.lua", run = "cd lua/fzy && make"}, {
--             "ray-x/go.nvim",
--             event = {"CmdlineEnter"},
--             ft = {"go", "gomod"},
--             build = ':lua require("go.install").update_all_sync()'
--         }, {
--             "ray-x/lsp_signature.nvim", -- Show function signature when you type
--             event = "VeryLazy",
--             config = function() require("lsp_signature").setup() end
--         }
--     },
--     config = function()
--         require("go").setup()
--         require("navigator").setup({
--             lsp_signature_help = true, -- enable ray-x/lsp_signature
--             lsp = {
--                 code_action = {enable = true, sign = true, sign_priority = 40, virtual_text = true},
--                 code_lens_action = {enable = true, sign = true, sign_priority = 40, virtual_text = true},
--                 document_highlight = true, -- LSP reference highlight,
--
--                 format_on_save = true,
--                 hover = {
--                   enable = true,
--                   -- fallback when hover failed
--                   -- e.g. if filetype is go, try godoc
--                   go = function()
--                     local w = vim.fn.expand('<cWORD>')
--                     vim.cmd('GoDoc ' .. w)
--                   end,
--                   default = function()
--                     -- fallback apply to all file types not been specified above
--                     -- local w = vim.fn.expand('<cWORD>')
--                     -- vim.lsp.buf.workspace_symbol(w)
--                   end,
--                 },
--             },
--         })
--     end,
}
